name = "final-siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [

  { pattern = "afrcloud.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "df.game.naver.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "zoomgov.com.afrcloud.biz.id", custom_domain = true }
  ]

[[kv_namespaces]]
binding = "SIREN"
id = "6c68f7e475004d49812776517b68f1c6"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/converter.html"
