name: cf workers

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and wasm-bindgen-cli
        run: |
          rustup update
          rustup target add wasm32-unknown-unknown
          cargo install -q wasm-bindgen-cli --version 0.2.102

      - name: Install worker-build
        run: cargo install -q worker-build

      - name: Build with worker-build (no wasm-opt)
        run: WASMOPT=0 worker-build --release

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
